name: Build

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y -o Acquire::Retries=50 \
                           pesign gcab gcc-aarch64-linux-gnu
      - name: Build
        working-directory: src
        run: |
          make
